### ISSUE TITLE
Old color in sidebar

### ISSUE THREAD

**Issue by vinzv** [siduction/calamares-settings-siduction#2]
The sidebar still has the wintersky background color:

![grafik](https://user-images.githubusercontent.com/74432/210873203-4c528ec6-bb8c-4dd5-9d3e-cbd980cba9c9.png)

**Comment by hhl** [comment]
sidebarBackground  "#013C58"

![farbw-013C58](https://user-images.githubusercontent.com/194791/211366782-45ebf20d-b654-434c-8762-e35bed1b519e.png)
